### ISSUE TITLE
Plot_DiffusionMap colour by phenotype

### ISSUE THREAD

**Issue by KatharinaKohler** [ChenWeiyan/LandSCENT#15]
Hi Weiyan, 

Thank you so much for previous help! Now the whole thing is working for me. 
I was just wondering whether there is the possibility to colour the dots according to phenotype information when doing the DiffusionMap?
I haven't found any solution so far. 

Best regards,
Katharina

**Comment by ChenWeiyan** [comment]
Hi Katharina,

Using the `Plot_DiffusionMap` function itself is difficult to color the dots by phenotype. But you can simply extract the DiffusionMap's coordinates from the final object after the DiffusionMap is done, with the following command:

`DM.coordinates <- DoDiffusionMap.o$DMEigen`

And you will find the coordinates in columns. Furthermore, if you want the DPT information, you can try the following:

`DPT <- destiny::DPT(DoDiffusionMap.o$DM, tips = DoDiffusionMap.o$root)`

Once you get the DiffusionMap's coordinates and so on, you can then plot the figure you need with general tools, say `ggplot2` etc.

Hope this be helpful,
Weiyan

**Comment by KatharinaKohler** [comment]
This is very helpful, thank you so much!

Best regards,
Katharina
