### ISSUE TITLE
Windows  does not support 'mc.cores' > 1

### ISSUE THREAD

**Issue by changtongwa** [ChenWeiyan/LandSCENT#16]
Used in version R-4.3.2，While running

SR.o <- CompSRana(Integration.l, local = TRUE, mc.cores = 8)
>Windows  does not support 'mc.cores' > 1

Is it possible  for me to use 8 cores for me to run the programe?

**Comment by ChenWeiyan** [comment]
The parallel mode in LandSCENT is performed by _mclapply_, which is not supported by Windows.

So you probably need to use Linux system or Mac to run 8 cores. Perhaps you can build up a virtual machine on your computer to achieve such goal.

Hope this helps!

**Comment by changtongwa** [comment]
Thank you.
 Can I still get the final result if I run with Windows single core?

**Comment by ChenWeiyan** [comment]
Sure you can. The time shall depend on the cell number.
