### ISSUE TITLE
DoIntegPPI gene identifier error 

### ISSUE THREAD

**Issue by haircell** [ChenWeiyan/LandSCENT#2]
Hi,

I was able to run through the demo smoothly. I'm now trying a subset of my own data (SmartSeq2, about 900 cells). I'm using the `SingleCellExperiment` class with gene symbols. I was able to obtain the EntrezIDs through `mapIds` feature of `AnnotationDbi`.  So I ultimately had EntrezIDs as row names (features/genes), and cell names as columns in my `sce`, which also contained additional metadata. 

I'm looking to use the PPI network provided within the package, so both are loaded:
`data(net13Jun12.m)`
`data(net17Jan16.m)`

My data is in `sce`, when I try running the following:
`Integration.l <- DoIntegPPI(exp.m = sce, ppiA.m = net17Jan16.m, log_trans = FALSE)`
I get:
```
Error in DoIntegPPI(exp.m = sce, ppiA.m = net17Jan16.m, log_trans = FALSE) : 
  scRNA-seq data should have the same gene identifier with the network!
```
I get the same error with `net13Jun12.m` and when I try to use a matrix of either `counts`, `normcounts`, or `logcounts` all extracted from `sce`.

Here are the first 5x5 of my data:
```
                A1               A3              A4                   A5              A6
14679     0.00               0              0                   0.00           57.15
12544    55.97               0              0                   0.00            0.00
14955     0.00               0              0                   0.00            0.00
107815    0.00               0              0                   0.00            0.00
67608     0.00               0              0                   3.23           46.02

```

Any help would be appreciated. Thank you.

**Comment by ChenWeiyan** [comment]
Hi,

I checked the gene ID you provided, and they are all from mouse. However the networks we provided are all homo-sapiens genes, so I think the answer is clear.

I suggest two ways of solving this:
1. You can find those homologous genes, could also be done with `AnnotationDbi` I think, and then use the network information we provided.
2. You can also construct a network yourself with mouse genes and then do all the same workflow.

Sorry we do not highlight the species of network, I will add such information soon.

Hope this would be helpful.

Weiyan

**Comment by haircell** [comment]
Ah, that makes sense! Thanks. 

Is there a workflow (or example) of how to create one of the PPI networks? I know the vignette mentions the sources it comes from, but would be great to have a work flow for updating purposes? Or a built in mouse network? 

Thanks again!

**Comment by ChenWeiyan** [comment]
Yeah, we plan to add some examples of the network. May also consider providing other networks.

You could check relevant updates in the following versions.

cheers,
Weiyan
