### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by jmzvillarreal** [ChenWeiyan/LandSCENT#4]
Hi,
I am running LandSCENT on a dataset of 5000 cells and the command CompSRana takes ages to run on a HP Z800 workstation with 10 cores assigned ... Is it normal ? how can I improve it in order to rerun some features or even bigger datasets?
By the way the results are great !
Thanks.
Jaime.

**Comment by ChenWeiyan** [comment]
Hi Jaime,
For your reference, I typically spend hours with 50 cores if there are more than 3000 cells. So I think it should take longer time with 10 cores for 5000 cells. I also tried on ~100k cells with 50 cores before, and it took me more than 12 hours.
The calculation time is definitely an important issue. But so far, we just used parallel package to accelerate the calculation, it could be potentially improved in future versions. Maybe incorporating C or Python modules...

Hope this be helpful.
Weiyan

**Comment by jmzvillarreal** [comment]
Hi Weiyan, 
I am trying to run a dataset of 13 000 cells in a cluster, assigning 200 cores and 1TB of memory and it is not enough still ... Is this normal ?? Could you specify the characteristics of the machine you ran those 100k cells ?
Thanks in advance.
Best, Jaime.
